version: '3.4'

networks:
  db-server:
    driver: bridge
  react-server:
  db-admin:
services:
  libraryproject:
    image: ${DOCKER_REGISTRY-}libraryproject
    depends_on:
      - "postgres_db"
    build:
      context: .
      dockerfile: LibraryProject/Dockerfile
    networks:
      - db-server
      - db-admin
    
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-server
      - db-admin
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db-admin
volumes:
  postgres_data:
  pgadmin-data:


